version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432

  localstack:
    image: localstack/localstack:latest
    ports:
      - 9000:8080
      - 4576:4576
      - 4575:4575
    environment:
      HOSTNAME_EXTERNAL: localstack
      DEFAULT_REGION: eu-west-2
      SERVICES: sns,sqs

  aws_cli:
    image: garland/aws-cli-docker
    command:
      - /bin/sh
      - -c
      - |
        aws --endpoint-url=http://localstack:4575 sns create-topic --name feedback_topic_ingress
        aws --endpoint-url=http://localstack:4575 sns create-topic --name feedback_topic_egress
        aws --endpoint-url=http://localstack:4575 sns list-topics
        aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name feedback_queue
        aws --endpoint-url=http://localstack:4576 sqs list-queues
        aws --endpoint-url=http://localstack:4575 sns subscribe --topic-arn arn:aws:sns:eu-west-2:000000000000:feedback_topic_ingress --protocol sqs --notification-endpoint arn:aws:sns:eu-west-2:000000000000:feedback_queue
        aws --endpoint-url=http://localstack:4575 sns list-subscriptions
    environment:
      AWS_ACCESS_KEY_ID: UNSET
      AWS_SECRET_ACCESS_KEY: UNSET
      AWS_DEFAULT_REGION: eu-west-2
    depends_on:
      - localstack
